config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create' 

   get '/longest_title' => 'chocolates#longest_title'
 
  resources :reviews
  resources :chocolates do #nest my review under chocolate, I want ability to review this chocolate by cliking the link thet will take me to nested rout chocolate/1/review/new
    resources :reviews, only: [:new, :index, :create]
  end
  resources :brands
  resources :users 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :reviewed_chocolates, through: :reviews, source: :chocolate 
    has_many :chocolates #that they have created user.chocolate
    
    validates :username, uniqueness: true,  presence: true 
    validates :email, uniqueness: true, presence: true
    
    has_secure_password 

    def self.create_by_github_omniauth(auth)
        self.find_or_create_by(uid: auth[:info][:id]) do |u|
          #User.where(uid: auth[:info][:id]).first_or_initialize
          u.password = SecureRandom.hex 
        end
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.valid?
          @user.save #if I can save user which means user is valid then we sign up user and redirect to his page show
          session[:user_id] = @user.id #sign up - log in user
          redirect_to user_path(@user) #his page show
        else
          render :new
        end
    end
    
    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id]) #difference between find_by don't give error like find, but redirect_to page i want 
    end

    private

    def user_params
      params.require(:user).permit(:username, :email, :password)#we take params and requie object that come through params and permit any other params we want
    #when I permit password I need to include in model has_secure password and uncomment in gemfile gem bcypt otherwise I will get error unknown attribute"password"
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render partial: 'layouts/errors', locals: {object: @user} %>

<%= form_for @user, controller: 'users', action: 'create'  do |f|%> <!--we use form_for becouse we are creating new user, in controller User.new-->
 <div class="form-group">
    <%= f.label :username, "Username:"%> 
    <%= f.text_field :username %>
  
    <%= f.label :email, "Email:" %>
    <%= f.email_field :email %>

    <%= f.label :password, "Password:" %>
    <%= f.password_field :password %>
</div>
  <div class="form-group">
    <label>
      <input type="checkbox"> Remember me
    </label>  
  </div>

<div class="field">
 
    <%= f.submit "Sign Up", class: "btn btn-default btn-primary" %>

</div>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username%>! </h1>
<div class="form-group">
<h3 style="text-indent: 40px">Here are the chocolates reviewed by you:</h3>
</div>
<br>
<ul>
  
  <% @user.reviews.each do |review| %>
  <div class="form-group">
  <li><%= link_to review.chocolate.title_and_brand, chocolate_path(review.chocolate) %> in <%= review.chocolate.category%> chocolates category. Your review is: <%= link_to review.title, review_path(review)%> - <%= review.rating.to_i%> <%= "star".pluralize(review.rating.to_i) %></li>
  </div>
 
  <% end %>
</ul>