config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create' 

   get '/longest_title' => 'chocolates#longest_title'
 
  resources :reviews
  resources :chocolates do #nest my review under chocolate, I want ability to review this chocolate by cliking the link thet will take me to nested rout chocolate/1/review/new
    resources :reviews, only: [:new, :index, :create]
  end
  resources :brands
  resources :users 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_review, only:[:show, :edit, :update]

    def new
        # if it's nested
        if params[:chocolate_id] && @chocolate = Chocolate.find_by_id(params[:chocolate_id])
            @review = @chocolate.reviews.build 
        else #if not nested
            @review = Review.new 
        end
    end

    def create 
        @review = current_user.reviews.build(review_params)
        if @review.save
          redirect_to review_path(@review) 
        else
          render :new
        end
    end

    def show
    end

    def index 
        if  params[:chocolate_id]
            @chocolate = Chocolate.find_by_id(params[:chocolate_id])
            @reviews = @chocolate.reviews 
        else
        #if it's not nested: /reviews
            @reviews = Review.all
        end
    end

    
    def edit
    end

    def update 
        if @review.update(review_params)
        redirect_to review_path(@review)
        else
        render :edit
        end
    end

    
    private

    def review_params
        params.require(:review).permit(:chocolate_id, :user_id, :content, :rating, :title)
    end
    
    def set_review
        @review = Review.find_by_id(params[:id])
        redirect_to reviews_path if !@review
    end


   
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  #on helpers folder controller can't access this is only for desplaying in view
#abstracting logic from views and use ruby code and we can't use here html tags
#helper methods is how something will be desplayed whereas model methods are doing staff like grabbing info from db and scope our model methods but our class level model methodes
def display_header(review)
      if params[:chocolate_id] 
          #we use content_tag then send information as arguments and use ruby type of interpolation instead erb type of interploation
          content_tag(:h1, "Add a Review for #{review.chocolate.title} -  #{review.chocolate.brand.name}")# desplay this if is nested
      else
        content_tag(:h1, "Create a review")# display this if not nested
      end
    end
end

# <% if params[:chocolate_id] %>
#   <h1>"Add a Review for <%=review.chocolate.title %> - <%= review.chocolate.brand.name %></h1>
# <% else %>
#   <h1>Create a review</h1>
# <% end %>

app/views/reviews/edit.html.erb
<h1>Edit <%= @review.title %></h1>

<%= form_for(@review) do |f|%>
  <% if params[:chocolate_id] %>
    <%= f.hidden_field :chocolate_id %>
  <% else %>
    <div class="form-group">
      <%= f.label :chocolate_id, "Select a Chocolate", class: "col-md-4 control-label" %>
      
      <%= f.collection_select :chocolate_id, Chocolate.alpha, :id, :title_and_brand, include_blank: true%>
      
    </div>

  <% end %>
  <br>
  
    <div class="form-group">
      <%= f.label :rating, "Rating", class: "col-md-4 control-label" %>
      <%= f.number_field :rating, min:0, max:5 %>
    </div>
 
    
  <br>
  <div class="form-group">
    <%= f.label :title, class: "col-md-4 control-label"  %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :content, class: "col-md-4 control-label"  %>
    <%= f.text_area :content, size: "25x5" %>
  </div>
  <br>
  <div class="form-group">
 
      <%= f.submit "Submit", class: "btn btn-default btn-primary " %>
   
  </div>
 
<% end %>

app/views/reviews/index.html.erb
<h1> All the Reviews</h1>
<% @reviews.each do |review| %>
<div class="form-group">
  <li>
  <%= review.chocolate.title%> in <%= review.chocolate.category%> chocolates category:
   <%= link_to review.title, review_path(review)%> - Rating: <%= review.rating.to_i %> <%= "star".pluralize(review.rating.to_i) %>
</div>
<% end %>

app/views/reviews/new.html.erb
<%=  display_header(@review)%>

<%= render partial: 'layouts/errors', locals: {object: @review} %>
<br>

<%= form_for(@review) do |f|%>
  <% if params[:chocolate_id] %><!--if it's neasted it will give hidden fiels otherwise it will give drop down selection-->
    <%= f.hidden_field :chocolate_id %>
  <% else %>
    <div class="form-group">
      <%= f.label :chocolate_id, "Select a Chocolate", class: "col-md-4 control-label" %>
      <%= f.collection_select :chocolate_id, Chocolate.alpha, :id, :title_and_brand, include_blank: true%><!--I want in drop down menye to desplay title and brend-->
    </div>
  <% end %>
  <br>
  
    <div class="form-group">
      <%= f.label :rating, "Rating", class: "col-md-4 control-label" %>
      <%= f.number_field :rating, min:1, max:5 %>
    </div>
 
    
  <br>
  <div class="form-group">
    <%= f.label :title, class: "col-md-4 control-label"  %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :content, class: "col-md-4 control-label"  %>
    <%= f.text_area :content, size: "25x5" %>
  </div>
  <br>
 
   
      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
   
 
<% end %>

<!--

f.hidden_field :chocolate_id will prepopulate chocolate_id which I have as attribute in tabel
 chocolate_reviews GET    /chocolates/:chocolate_id/reviews(.:format)   reviews#index
                  POST   /chocolates/:chocolate_id/reviews(.:format)    reviews#create
  new_chocolate_review GET    /chocolates/:chocolate_id/reviews/new(.:format)    reviews#new            

-->

app/views/reviews/show.html.erb
<h1 ><%= @review.title%> -  

<% @review.rating.to_i.times do  %>
 <span class="glyphicon glyphicon-star"></span>
<% end %>
<% @review.blank_stars.times do %>
 <span class="glyphicon glyphicon-star-empty"></span>
<% end %>
</h1>

<p><%= @review.content%></p>
<br>
<strong><%= link_to "Edit Review", edit_review_path(@review.id) if @review.user == current_user%></strong>