config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create' 

   get '/longest_title' => 'chocolates#longest_title'
 
  resources :reviews
  resources :chocolates do #nest my review under chocolate, I want ability to review this chocolate by cliking the link thet will take me to nested rout chocolate/1/review/new
    resources :reviews, only: [:new, :index, :create]
  end
  resources :brands
  resources :users 
end

app/views/layouts/_errors.html.erb
<% if object.try(:errors).try(:any?) %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_loggedin_links.html.erb
<nav>
  <%= link_to "Log Out", logout_path, method: :delete, class: "btn btn-primary"%> <!--by difolt logout_path will be get request, i need jquery for this method delete-->
  <%= link_to "Home", user_path(current_user), :class => "btn btn-primary"%>
  <%= link_to "Longest Title", longest_title_path, :class => "btn btn-primary"%>
  <%= link_to "Add a Chocolate", new_chocolate_path, :class => "btn btn-primary" %> 
  <%= link_to "All Chocolates", chocolates_path, :class => "btn btn-primary" %> 
  <%= link_to "All Brands", brands_path, :class => "btn btn-primary" %>  
  <%= link_to "Add a Review", new_review_path, :class => "btn btn-primary" %> 
  <%= link_to "All Reviews", reviews_path, :class => "btn btn-primary" %> 
</nav>

app/views/layouts/_loggedout_links.html.erb
<nav>
  <%= link_to "Log In", login_path, :class => "btn btn-primary" %>
  <%= link_to "Log In via Github", "/auth/github", :class => "btn btn-primary" %> <!--we don't need in routes.rb route for this becouse that piece gets taken care of by our omniouth.rb file but we need rout to handel the callback, when GitHub senda us get request we need a rout to direct where that supposed to go-->
  or
  <%= link_to "Sign Up", signup_path, :class => "btn btn-primary" %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ChocolateFansApp</title>
     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS--> 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class='container'>
  <header>
  
 </header>
  <div><%= render_nav_bar %></div>
  <body>
  <div class="wrapper">

    <%= yield %>
  </div>
    
  </body>
</html>