config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create' 

   get '/longest_title' => 'chocolates#longest_title'
 
  resources :reviews
  resources :chocolates do #nest my review under chocolate, I want ability to review this chocolate by cliking the link thet will take me to nested rout chocolate/1/review/new
    resources :reviews, only: [:new, :index, :create]
  end
  resources :brands
  resources :users 
end

app/models/chocolate.rb
class Chocolate < ApplicationRecord
  belongs_to :brand 
  belongs_to :user 
  has_many :reviews
  has_many :users, through: :reviews 
  has_one_attached :image

  accepts_nested_attributes_for :brand 

  validates :title, :category, :description, presence: true 
  validate :not_a_duplicate 
  validate :acceptable_image
  #validates :title uniquness: {scope: :brand} but we made validate :not_a_duplicate as custom one
  
  
  scope :order_by_rating, -> {left_joins(:reviews).group(:id).order('avg(rating) desc')}
  
  def self.alpha
    order(:title) 
  end


  #It would make more sense to write max_characters as a class method since we are dealing with all the Chocolates and not one instance chocolate.
  
  def self.max_characters
    self.pluck(:title).max_by(&:length)
  end
  #Chocolate.max_characters.

  # def max_characters
  #   chocolate = Chocolate.pluck(:title).max_by(&:length)
  # end
  
  def brand_attributes=(attributes)
    self.brand = Brand.find_or_create_by(attributes) if !attributes['name'].empty?
    self.brand
  end

  def thumbnail
    self.image.variant(resize: "300x300")
  end

  def acceptable_image
    return unless image.attached?
  
    unless image.byte_size <= 1.megabyte
      errors.add(:image, "is too big")
    end
  
    acceptable_types = ["image/jpeg", "image/png"]
    unless acceptable_types.include?(image.content_type)
      errors.add(:image, "must be a JPEG or PNG")
    end
  end

  def not_a_duplicate 
     chocolate = Chocolate.find_by(title: title, brand_id: brand_id) 
      if !!chocolate && chocolate != self
      errors.add(:title, 'has already been added for that brand')
    end
  end

  def brand_name
    brand.try(:name)
  end

  def title_and_brand 
    "#{title} by #{brand.try(:name)}"
  end


end

app/controllers/chocolates_controller.rb
class ChocolatesController < ApplicationController
    before_action :set_chocolate, only:[:show, :edit, :update]
    before_action :redirect_if_not_logged_in

    def index
        @chocolates = Chocolate.order_by_rating.includes(:brand)
    end

    def show
    end

    def new
        @chocolate = Chocolate.new
        @chocolate.build_brand
    end


    def create
         @chocolate = current_user.chocolates.build(chocolate_params)
        if @chocolate.save 
            @chocolate.image.purge
            @chocolate.image.attach(params[:chocolate][:image])
            redirect_to chocolate_path(@chocolate)
        else
            @chocolate.build_brand
            render :new
        end
    end

    def edit
    end

    def update
        if  @chocolate.update(chocolate_params)
            redirect_to chocolate_path(@chocolate)
        else
            render :edit
        end  
    end
   
    def longest_title 
    end
        
    private


    def chocolate_params
        if params[:chocolate][:image]==""
            params.require(:chocolate).permit(:title, :category, :description, :user_id, :brand_id,   brand_attributes: [:name])
        else
            params.require(:chocolate).permit(:title, :category, :description, :user_id, :brand_id, :image,  brand_attributes: [:name])#brand_attributes: [:name] becouse of neasted form
        end
    end


    def set_chocolate
        @chocolate = Chocolate.find_by_id(params[:id])
        redirect_to chocolates_path if !@chocolate
    end
end

app/helpers/chocolates_helper.rb
module ChocolatesHelper
end

app/views/chocolates/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @chocolate}  %>

<%= form_for(@chocolate) do |f|%>
  <div class="form-group">
    <%= f.label :title, class: "col-md-4 control-label"  %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :category, class: "col-md-4 control-label"  %>
    <%= f.select :category, options_for_select(["Milk", "Dark", "White", "Caramels", "Biscuity", "Fruity&Nutty", "Others" ], selected: @chocolate.category)%>
 </div>
  <br>
  <div class="form-group">
    <%= f.label :description, class: "col-md-4 control-label"  %>
    <%= f.text_area :description, size: "25x5" %>
  </div>

 
  <div class="form-group">
    <%= f.label :image, class: "col-md-4 control-label"  %>
    <%= f.file_field :image %><!--The only difference with other helpers is that you cannot set a default value for file inputs as this would have no meaning.https://guides.rubyonrails.org/v3.1/form_helpers.html-->
  </div>

  <div class="form-group">
    <%= f.label :brand, "Select a Brand that already exists:", class: "col-md-4 control-label"  %>
    <%= f.collection_select :brand_id, Brand.all, :id, :name, include_blank: true,  class: "col-md-4 control-label" %>
    <!--f is object, method is brand.id, collection is Brand.all,value that send to params is :id, desplayed is :name)   -->
  </div>

 
  <div class="form-group" >
    <%=f.fields_for :brand do |b| %> <!--we need to be able to write attributes of another objects which means this needs to be a nested form-->
      <%= b.label :name, "Or create a new Brand:", class: "col-md-4 control-label"  %>
      <%= b.text_field :name, value: '' %>
    <% end %>
  </div>
  
  <br>

  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
<% end %>

app/views/chocolates/edit.html.erb
<h1>Edit your Chocolate</h1>

<%= render partial: 'form' %>

app/views/chocolates/index.html.erb
<h1>All the Chocolates</h1><br>


<% @chocolates.each do |chocolate| %>
<div class="form-group">
  <h2><strong><%= link_to chocolate.title, chocolate_path(chocolate.id)%>  -  <%= chocolate.brand.name %></strong></h2>
</div>   
  <div class="form-group">
    <strong>Category:</strong> <%= chocolate.category %>
  </div>

 <div class="form-group">
    
    <strong>Description:</strong> <%= chocolate.description %>
  </div>

 <div class="form-group">
  <% if chocolate.reviews.exists? %>
    <strong>Avgerage Rating: <%= chocolate.reviews.average(:rating).round(1) %> <%= "star".pluralize(chocolate.reviews.average(:rating).round(1)) %></strong>
  <% end %>
  </div>
<br>

  <div class=img>
  <% if chocolate.image.attached? %>
    <%= image_tag url_for(chocolate.thumbnail)%> 
  <% end %>
  </div>
<br>
<div class="form-group">
  <strong><%= link_to "Write a review", new_chocolate_review_path(chocolate.id)%></strong> <!--I can have this link thanks to nested route path is new_chocolate_review_path and I have to pass in id - chocolate.id-->

</div> 
<br>

<br>

<% end %>

app/views/chocolates/longest_title.html.erb
<p>Chocolate with longest title: <%= Chocolate.max_characters %>  </p> 

app/views/chocolates/new.html.erb
<section>
<h1>Make a new chocolate!</h1>
<%= render partial: 'layouts/errors', locals: {object: @chocolate} %>

<%= form_for(@chocolate) do |f|%>
  <div class="form-group">
    <%= f.label :title, class: "col-md-4 control-label"  %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :category, class: "col-md-4 control-label"  %>
    <%= f.select :category, options_for_select(["Milk", "Dark", "White", "Caramels", "Biscuity", "Fruity&Nutty", "Others"]), include_blank: 'Select One' %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :description, class: "col-md-4 control-label"  %>
    <%= f.text_area :description, size: "25x5" %>
  </div>

  <div class="form-group">
    <%= f.label :image, class: "col-md-4 control-label"  %>
    <%= f.file_field :image %>
   </div>

  <div class="form-group">
    <%= f.label :brand, "Select a Brand that already exists:", class: "col-md-4 control-label"  %>
    <%= f.collection_select :brand_id, Brand.all, :id, :name, include_blank: 'Select One', class: "col-md-4 control-label" %>
    <!--whenever we want to select from something that already exist and drop down collection select works well
    f is object, method is brand.id and that is attribute I want to asign and that method is coming from belongs_to relationship, collection is Brand.all,value that send to params is :id, desplayed is :name)   -->
  </div>

  <div class="form-group" >
    <%=f.fields_for :brand do |b| %> <!--user have to be able to fill in name of brand, user need to be able to write attributes of another objects which means this needs to be a nested form and nested form stars with fields_for something else i this case for brand-->
      <%= b.label :name, "Or create a new Brand:", class: "col-md-4 control-label"  %><!--in inspect this is label for chocolate_brand_attributes_name-->
      <%= b.text_field :name %><!--in inspect input name=chocolate[brand_attributes][name]-->
    <% end %>
  </div>
  <br>

  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
<% end %>

</section>

<!--
collection_select is intended to be used when the list of items is an array of ActiveRecord objects. 
collection_select is built on the top of select so it's a convenient method when you need to display a collection of objects and
 not an array of strings. And regarding select , you can use it with a Hash.
-->

app/views/chocolates/show.html.erb
<h1><%= @chocolate.title%>  </h1>

<div class="form-group">
<% if @chocolate.image.attached? %>
  <%= image_tag url_for(@chocolate.thumbnail) %>
<% end %>
</div>

 <div class="form-group">
  <strong>Brand: <%= @chocolate.brand.name %></strong> 
</div>
  <div class="form-group">
    <strong>Category:</strong> <%= @chocolate.category %>
</div>


 <div class="form-group">
   <strong>Description:</strong> <%= @chocolate.description %>
</div>

<br>
<strong> Added by: <%= @chocolate.user.username %></strong>
<br><br>
<strong><%= link_to "Edit chocolate", edit_chocolate_path(@chocolate) if @chocolate.user == current_user%></strong>
<br><br>
<strong><%= link_to "See all Reviews", chocolate_reviews_path(@chocolate) %></strong><!--this links I have becouse of nested rout and index action in reviews_controller in part if it's nested-->

<style> 
  img { 
    float: left;  
    margin-right: 50px;
    padding-right: 20px;         
  } 
  p { 
    text-align: left; 
    font-size: 25px; 
  }         
</style> 
     
       
        